### ISSUE TITLE
Please add release tag

### ISSUE THREAD

**Issue by tillea** [narunlifescience/runcircos-gui#1]
Hi,
I consider to package runcircos-gui for Debian.  To do so it would help a lot if you would add a release tag to specify the version number.  This will help Debian maintainers to automatically detect new versions of software to stay up to date with the packaged code.
Thanks for considering, Andreas.

**Comment by tillea** [comment]
Hi again,
it would help if you woule confirm whether you consider release tags a good idea in general and just have no idea how to do or whether you do not intend to set tags at all.
Kind regards, Andreas.

**Comment by narunlifescience** [comment]
Hi.. I am afraid runcircos-gui may not have a user base for a release.

**Comment by tillea** [comment]
On Sat, Sep 08, 2018 at 02:17:37AM -0700, Arun Narayanankutty wrote:
> Hi.. I am afraid runcircos-gui may not have a user base for a release.
I've created the Debian package due to user request.  May be you are underestimating the user base and in general it is a good idea to tag releases anyway.

**Comment by narunlifescience** [comment]
made a pre release version, hope that is enough.

**Comment by tillea** [comment]
On Sun, Sep 09, 2018 at 01:46:04PM -0700, Arun Narayanankutty wrote:
> made a pre release version, hope that is enough.
Thanks a lot, Andreas.
